version: "3.9"

services:
  zerodeploy:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: zerodeploy-dev
    ports:
      - "${ZERO_DEPLOY_PORT:-8080}:8000"
    environment:
      - DOMAIN_SUFFIX=${DOMAIN_SUFFIX:-}
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./app:/app
      - /app/__pycache__
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge

volumes:
  zerodeploy-pip-cache:
    driver: local